name: Test

on:
  workflow_dispatch:
    inputs:
      run_nancy:
        description: 'Run Nancy'
        type: boolean
        required: true
      run_gosec:
        description: 'Run Gosec'
        type: boolean
        required: true
  pull_request:
    types: [opened, synchronize]
  schedule:
    - cron: '0 7 * * 1-5' # Every day at 7am UTC, it will trigger the workflow on the default branch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: 1.20.11
  API_COVERAGE_MIN_THRESHOLD: 80
  SDK_COVERAGE_MIN_THRESHOLD: 72
  MASTER_API_COVERAGE: ${{ vars.MASTER_API_COVERAGE }}
  MASTER_SDK_COVERAGE: ${{ vars.MASTER_SDK_COVERAGE }}

jobs:

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: Print variables
        shell: bash
        run: |
            echo run_nancy: ${{ github.event.inputs.run_nancy }}
            echo run_gosec: ${{ github.event.inputs.run_gosec }}
            echo event_name: ${{ github.event_name }}
            echo run_gosec: ${{ github.event_name == 'schedule' }} 
            echo right_side: (${{ github.event_name == 'workflow_dispatch' }} && ${{ github.event.inputs.run_nancy == 'true'}})
          
            

  run_nancy:
    if: ${{ github.event_name == 'schedule' }} || (${{ github.event_name == 'workflow_dispatch' }} && ${{ github.event.inputs.run_nancy == 'true'}})
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Write Go List
        run: go list -json -deps ./... > go.list

      - name: Running Nancy
        uses: sonatype-nexus-community/nancy-github-action@main
        with:
          nancyCommand: sleuth --exclude-vulnerability-file=.nancy-ignore

  run_gosec:
    if: ${{ github.event_name == 'schedule' }} || (${{ github.event_name == 'workflow_dispatch' }} && ${{ github.event.inputs.run_gosec == 'true' }})
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: '-exclude-generated ./...'
